### ISSUE TITLE
Error: Forbidden

### ISSUE THREAD

**Issue by honestyan** [RomanHotsiy/commitgpt#15]
This error comes right after executing commitgpt even when my token doesn't wrong. No further logs appear.

![ss3](https://user-images.githubusercontent.com/37909888/206492067-a482d53d-c6ca-430d-b6d3-3316c4c4b304.JPG)

**Comment by adamaltman** [comment]
Did you hit the chat GPT rate limit?

**Comment by RomanHotsiy** [comment]
@honestyan I just published an ew version which should print more details: 1.0.4.
Try it out plz.

**Comment by RomanHotsiy** [comment]
Says the request is blocked.

Remove rm `~/.commit-gpt.json` file. It will ask you for the new token on the next run.
