### ISSUE TITLE
"ask for more ideas" produces rubbish

### ISSUE THREAD

**Issue by vaspoz** [RomanHotsiy/commitgpt#19]
When I used "ask for more ideas", got this output:
![image](https://user-images.githubusercontent.com/4658186/206696190-740d4cf2-b9d3-4102-8e80-7e9419a131d1.png)

And it's not only completely unrelated to the changes, but also unrelated to each other =

**Comment by RomanHotsiy** [comment]
Yeah, sometimes it produces good results, sometimes rubbish. I'll play with chatgpt queries more to get something more useful.

Thanks!

**Comment by vaspoz** [comment]
@RomanHotsiy , up to you then - you can close that issue

**Comment by RomanHotsiy** [comment]
Fixed in 2.0.0 by https://github.com/RomanHotsiy/commitgpt/pull/27
