### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by omarshaarawi** [RomanHotsiy/commitgpt#2]
Just a couple of suggestions to fix in the README.md.

1. In `config.ts` , the config file that is being looked at is `~/{HOME_DIR}/.commit-gpt.json`. There isn't any mention of a `config.json` mentioned in the code base like it says in the README
2. The key that it's looking for is `sessionKey` not the snake case version `session_key` 
3. Huge nitpick so ignore but your code runs `git diff --cached` which I just learned is no different than `git diff --staged`. However, maybe consider updating so it matches?

All nitpicks as I was having trouble getting this working without digging into the code to figure out what was expected. 

For point 1 and 2, I know that if the config file doesn't exist, the it'll prompt to paste in the session key. This may be a separate issue but my terminals hung when trying to paste it in. I didn't want to create a separate issue yet until I confirmed it's not an issue I'm only experiencing.

**Comment by RomanHotsiy** [comment]
Thanks for the report! I'll take a look into it and get back to you.
