### ISSUE TITLE
🐛 New generated __Secure-next-auth.session-token are not accepted

### ISSUE THREAD

**Issue by sapirgolan** [RomanHotsiy/commitgpt#21]
I've tried running the app for the first time now,
I copied the value of `__Secure-next-auth.session-token` and pasted into the terminal and I get an error message: 
```
Invalid token. Please try again.
```

I think it happens since OpenAI has added **cloudflare** to protect their services
Using version _1.0.5_

**Comment by xremix** [comment]
I got the same issue since today. The auth on one machine still works, but on another machine where I wanted to authenticate the first time today it doesn't work anymore.

**Comment by RomanHotsiy** [comment]
Duplicated of #22
