### ISSUE TITLE
Unclear readme.md

### ISSUE THREAD

**Issue by slim16165** [RomanHotsiy/commitgpt#26]
Hi,

I've copied the content of the [readme.md](https://raw.githubusercontent.com/RomanHotsiy/commitgpt/main/README.md) in chat GPT 4 asking him: 

> Can you understand where I should write this command? npx commitgpt

:D

Here its answer (I guess he is right but it would be great if you could clarify those instructions inside the readme. Most of people, and even dev, have no idea what npx is for example):

You should write the command npx commitgpt in your terminal or command prompt. Here's how you can do it:

Open a terminal (on macOS or Linux) or command prompt (on Windows).
Navigate to the directory where your Git repository is located. You can use the cd command followed by the directory path. For example:

`cd path/to/your/git/repo`

Run the npx commitgpt command:

`npx commitgpt`

This command will execute the commitgpt tool, which will automatically generate commit messages for your staged changes using 

ChatGPT.

Note that you need to have [Node.js](https://nodejs.org/) and [npm](https://www.npmjs.com/) installed on your system to use the npx command.

**Comment by RomanHotsiy** [comment]
I'm not sure what to change here.
