### ISSUE TITLE
Invalid token. Please try again.

### ISSUE THREAD

**Issue by Gaibhne** [RomanHotsiy/commitgpt#5]
Every time I try. I follow the instructions to the letter, no idea why it isn't working. Anything I can do to help debug, please let me know.

**Comment by davidepaci** [comment]
Same here!

**Comment by RomanHotsiy** [comment]
Should be fixed by https://github.com/RomanHotsiy/commitgpt/pull/4

Try the new version v1.0.2

**Comment by douglasjunior** [comment]
Same here:

![image](https://user-images.githubusercontent.com/1512341/207610756-ddd4c928-9b22-4b1b-ad1f-d2bb344e6753.png)

**Comment by Lippiece** [comment]
Hey, @RomanHotsiy, I'm getting this too now, exactly as people describe.
