### ISSUE TITLE
No "imperative" commit message mode

### ISSUE THREAD

**Issue by Gaibhne** [RomanHotsiy/commitgpt#6]
Really by default, commit messages should appear in the imperative: instead of "Added logging", the subject should read "Add logging". See:

https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/
https://cbea.ms/git-commit/
https://reflectoring.io/meaningful-commit-messages/
https://www.gitkraken.com/learn/git/best-practices/git-commit-message

And many similar. The `-c` flag seems to already do that (unless it happened randomly during my tests), but many (most ?) people use simple, capitalized imperative subjects outside of `conventional commits` - basically, like the existing default, but with the imperative mood.

Could be a new mode, a flag, or simply a change to the default behaviour.

Otherwise: wow, this is so neat! Thank you!

**Comment by RomanHotsiy** [comment]
Nice idea. I'll try to add it on the next weekend.

**Comment by jineshqa** [comment]
Something that many companies use to track commits related to a Jira ticket would also be helpful. For example our commit message look like,

`APT-1234: Commit message`

Here is APT-1234 is the ticket number.

**Comment by rpdelaney** [comment]
@jineshqa  please create a separate issue for your suggestion.

**Comment by jineshqa** [comment]
Sure, thank you.

**Comment by RomanHotsiy** [comment]
Fixed in 2.0.0 by https://github.com/RomanHotsiy/commitgpt/pull/27 by introducing the template.
